spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://db.kpgpidlidbfpiokpdmev.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Lab6DAO!...

spring.datasource.driver-class-name=org.postgresql.Driver